version: "3.8"
services:
  mysql-db:
    image: "mysql:latest"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student
  web-app:
    image: "ntloc/web-app-fullstack-springboot-angular:22.11.2021.3.30.25"
    ports:
      - "8080:8080"
    restart: "always"
    environment:
      MYSQL_HOST: mysql-db