version: "3.8"
services:
  web-app:
    image: ntloc/web-app-fullstack-springboot-angular:2023.03.03.09.30.28
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: "always"
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student
    restart: unless-stopped
volumes:
  data: