version: "3.8"
services:
  web-app:
    image: "ntloc/web-app-fullstack-springboot-angular:22.11.2021.3.30.25"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
