version: "3.8"
services:
  web-app:
    image: "ntloc/web-app-fullstack-springboot-angular:1.12.2021.15.8.7"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
