version: "3.8"
services:
  web-app:
    image: ntloc/web-app-fullstack-springboot-angular:2023.03.03.09.21.10
    ports:
      - "8080:8080"
    restart: "always"
#    environment:
#      SPRING_PROFILES_ACTIVE: dev
