version: "3.8"
services:
  web-app:
    image: "ntloc/web-app-fullstack-springboot-angular:2.12.2021.15.5.12"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
