version: "3.8"
services:
  web-app:
    image: "ntloc/web-app-fullstack-springboot-angular:2.3.2023.14.0.11"
    ports:
      - "8080:8080"
    restart: "always"
#    environment:
#      SPRING_PROFILES_ACTIVE: dev
