# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy CD

on:
  push:
    branches: [ master ]

env:
  MYSQL_DATABASE: student
  MYSQL_ROOT_PASSWORD: password
  #AWS & Elastic Beanstalk
  AWS_REGION: ap-southeast-1
  EB_ENVIRONMENT_NAME: Webappfullstack-env
  EB_APPLICATION_NAME: Web App Fullstack
  EB_DEPLOYMENT_PACKAGE: aws-elasticbeanstalk/docker-compose.yml
jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64, Fullstack_Runner]
    steps:
      - uses: actions/checkout@v2

#      - name: Generate build number
#        id: build-number
#        run:  echo "BUILD_NUMBER=$(Get-Date -UFormat "%Y.%m.%d.%H.%M.%S").ToString()" >> $GITHUB_OUTPUT
      - name: Generate build number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(Get-Date -UFormat "%Y.%m.%d.%H.%M.%S")"

      - name: Get build number
        run: echo "The build number is ${{ steps.build-number.outputs.BUILD_NUMBER }}"

      - name: Update and commit app version in docker-compose.yaml
        run: |
          echo "Before update build number aws-elasticbeanstalk/docker-compose.yml
          cat aws-elasticbeanstalk/docker-compose.yml)
          $content = Get-Content "aws-elasticbeanstalk/docker-compose.yml"
          $content = $content -replace "(ntloc/web-app-fullstack-springboot-angular:)([^\s]+)_\1", "${{ steps.build-number.outputs.BUILD_NUMBER }}"
          Set-Content "aws-elasticbeanstalk/docker-compose.yml" $content
          echo "After update aws-elasticbeanstalk/docker-compose.yml
          cat aws-elasticbeanstalk/docker-compose.yml)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add aws-elasticbeanstalk/docker-compose.yml
          git commit -m "new app version: ${{steps.build-number.outputs.BUILD_NUMBER}}"
          git push

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Maven Clean Package and Push Image to Docker Hub
        run: mvn clean package -P build-frontend -DskipTests
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/web-app-fullstack-springboot-angular:${{steps.build-number.outputs.BUILD_NUMBER}}
      - name: Deploy to Server
        working-directory: aws-elasticbeanstalk
        run: docker compose up -d
