# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy CD

on:
  push:
    branches: [ master ]

env:
  MYSQL_DATABASE: student
  MYSQL_ROOT_PASSWORD: password
  #AWS & Elastic Beanstalk
  AWS_REGION: ap-southeast-1
  EB_ENVIRONMENT_NAME: Webappfullstack-env
  EB_APPLICATION_NAME: Web App Fullstack
  EB_DEPLOYMENT_PACKAGE: aws-elasticbeanstalk/docker-compose.yml
jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64, Fullstack_Runner]
    steps:
      - uses: actions/checkout@v2

      - name: Generate build number
        id: build-number
        run:  echo "BUILD_NUMBER=$(Get-Date -UFormat "%Y.%m.%d.%H.%M.%S").ToString()" >> $GITHUB_OUTPUT

      - name: Get build number
        run: echo "The selected number is ${{ steps.build-number.outputs.BUILD_NUMBER }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Maven Clean Package and Push Image to Docker Hub
        run: mvn clean package -P build-frontend -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/web-app-fullstack-springboot-angular:${{steps.build-number.outputs.BUILD_NUMBER}}

      - name: Update and commit app version in docker-compose.yaml
        run: |
          echo -e "Current aws-elasticbeanstalk/docker-compose.yml\n$(cat aws-elasticbeanstalk/docker-compose.yml)"
          sed -i -E 's_(ntloc/web-app-fullstack-springboot-angular:)([^"]*)_\1'${{steps.build-number.outputs.BUILD_NUMBER}}'_' aws-elasticbeanstalk/docker-compose.yml
          echo -e "Current aws-elasticbeanstalk/docker-compose.yml\n$(cat aws-elasticbeanstalk/docker-compose.yml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add aws-elasticbeanstalk/docker-compose.yml
          git commit -m "new app version: ${{steps.build-number.outputs.BUILD_NUMBER}}"
          git push
      - name: Deploy to Server
        working-directory: aws-elasticbeanstalk
        run: docker compose up -d
